### ISSUE TITLE
Folder structure

### ISSUE THREAD

**Issue by larshp** [SAP/abap-file-formats#109]
Example: https://github.com/SAP/abap-file-formats/tree/main/file-formats/chkc

it contains
![image](https://user-images.githubusercontent.com/5888506/124973457-d794c980-e02b-11eb-9eab-2f517d318f84.png)

the source is under `type` and the first file in the folder is the auto generated json schema file

Suggest:
A: Move the ABAP source to the root of the object type folder
B: Move the auto generated json schema to a new folder `generated` under the object type
C: Change the filename of the auto generated json schema, eg `zif_atc_aff_chkc_v1.json` to make it easier for users to tell the relationship between files

**Comment by larshp** [comment]
alternatively, move the ABAP type to the same folder level as the generated JSON

**Comment by albertmink** [comment]
We could start with option B. The folder name would suggest not to edit the json-schema manually as raised in #110.

**Comment by schneidermic0** [comment]
As long as we keep the reference to the schema file (jn the `$schema` field) we should be careful with names and folders.

I would prefer not to use the interface name for the json-schema file. At least as long as we are referring to it in the files. But we should add the version (like `chkc-v1.json` or `chic.v1.json`)

But, maybe, it makes sense to move all generated json schemas to one dedicated folder and keep the folder structure of object types only for the ABAP types, the format documentation and the example. E.g., `/schema/chkc-v1.json`.

**Comment by larshp** [comment]
I'd like to remove the `$schema` field and add a `version` field instead, https://github.com/SAP/abap-file-formats/issues/53

**Comment by schneidermic0** [comment]
Let's continue with this issue as soon as #53 is solved.

**Comment by albertmink** [comment]
Update:
- JSON data do no longer contain a `$schema` with url, replaced by `formatVersion` https://github.com/SAP/abap-file-formats/blob/main/file-formats/intf/examples/z_aff_example_intf.intf.json#L2
- JSON Schema has comment about autogenerated file https://github.com/SAP/abap-file-formats/blob/main/file-formats/intf/intf-v1.json#L2
- Readme got restructured a lot and is the main entry point for a particular object type

I feel as if the above discussion is outdated, due to the evolution of the repository and will close the issue.
Feel free to reopen the issue :wave:
