### ISSUE TITLE
DDLS: Update documentation: new file extension in CDS

### ISSUE THREAD

**Issue by albertmink** [SAP/abap-file-formats#161]
With the definition of a ABAP file format for CDS it is introduced a new file extension, see #160 

Let's document the new one here
https://github.com/SAP/abap-file-formats/blob/main/doc/specification.md#file-extensions

**Comment by BeckerWdf** [comment]
See also the discussions in: https://github.com/SAP/abap-file-formats/pull/160#issuecomment-898394272

Questions raised there are:

1. Is ABAP flavoured CDS a subset or superset of the other CDS?
2. Do you want to register different parsers for different ABAP flavoured CDS object types like DDLS, DCLS, DDLX, ...?
3. Do we want to keep the pattern <object_type>.<language>?
4. Do we break the pattern <object_type>.<language> when both are identical.

**Comment by BeckerWdf** [comment]
> See also the discussions in: [#160 (comment)](https://github.com/SAP/abap-file-formats/pull/160#issuecomment-898394272)
> 
> Questions raised there are:
> 
> 1. Is ABAP flavoured CDS a subset or superset of the other CDS?

It's both. ABAP flavoured CDS does not implement the complete CDS specification (e.g. no structured types up to now). And it has ABAP specific extensions (like the usage of ABAP data elements.
> 2. Do you want to register different parsers for different ABAP flavoured CDS object types like DDLS, DCLS, DDLX, ...?

At least ADT has a separate (RND based) parser for each CDS object type. So the answer it most probably: Yes.
> 3. Do we want to keep the pattern object_type.language?
> 4. Do we break the pattern object_type.language when both are identical?

These two are a matter of taste.

An by the way. What's the correct extension then for the ´.objectdependencies.json´ file?
´<name>.objectdependencies.json´ or ´<name>.ddls.objectdependencies.json´?

**Comment by schneidermic0** [comment]
> An by the way. What's the correct extension then for the ´.objectdependencies.json´ file?
´.objectdependencies.json´ or ´.ddls.objectdependencies.json´?

@BeckerWdf  From my point of view, it would be ´.ddls.objectdependencies.json´. See https://github.com/SAP/abap-file-formats/blob/main/doc/specification.md#content-type

**Comment by larshp** [comment]
should the title of this isuse be updated? "Update documentation: new file extension in CDS", its more a question of first finding the file extension?

**Comment by larshp** [comment]
having undecided file extensions and moving forward will,
- promote the use of the extension, making it more difficult to change the extension
- will promote building of syntax highlighting for a new language, which already exists
- tooling will be released which we cannot influence, making it a requirement for all tooling to handle possible legacy filenaming

**Comment by BeckerWdf** [comment]
> having undecided file extensions and moving forward will,
Which file extension is undecided?

**Comment by larshp** [comment]
".cds"

**Comment by BeckerWdf** [comment]
So what do you not like with the ".cds" extension?
For ABAP source code it's ".abap" so ".cds" sounds logical.

**Comment by larshp** [comment]
see comments in https://github.com/SAP/abap-file-formats/pull/160

**Comment by schneidermic0** [comment]
Are we talking about a decision between the following two options?

Option A: Currently, the pushed file extensions for CDS source code in this repository is `.cds`.

Option B: As far as I understand @larshp suggests to use `.acds` or something similar (as mentioned in https://github.com/SAP/abap-file-formats/pull/160#issuecomment-898394272) in order to differentiate between ABAP CDS and (e.g.) CAP's CDS.

**Comment by larshp** [comment]
Option C: "asddls", "asdcls", "asddlxs"

All options have different impact and tasks to be done to support the language

**Comment by schneidermic0** [comment]
@BeckerWdf @larshp Let's have a look at this topic in our next sync meeting

**Comment by larshp** [comment]
- "obj.ddls.cds"
- "obj.ddlx.cds"

**Comment by schneidermic0** [comment]
We had just our sync meeting with @larshp and @BeckerWdf.

We came to the conclusion that we shall go for option B: The file extension for the source code of `DDLS` objects (as well as other CDS related object types) shall be `.acds` in the future.

Some additional information on the decision:

- We choose `.acds` instead of `.cds` to indicate ABAP's "dialect" of core data services (CDS).
- We also discussed whether it makes sense to have a dedicated file extension for `DDLS`, `DDLX`, .... We decided to keep it similar to ABAP source code artefacts (like programs, classes, interfaces, ...) to have just one file extension.
- Very likely, we will need a new file extension for objects like behaviour definitions or service definitions.
