### ISSUE TITLE
Question about repo

### ISSUE THREAD

**Issue by drakth** [SAP/abap-file-formats#273]
I've been looking at this project for last few days and seems interesting, I was thinking about doing a new object type (DOMA maybe?), however, from what I've seen the only way to know if my code is OK would be to do a Pull Request, is this correct? Or is there any other way to check my code?
Thank you.

**Comment by schneidermic0** [comment]
Welcome, Matias :)

Thank you for your interest in ABAP file formats. I am happy to hear you are considering to contribute to our project.

You are right, the best way to validate your changes is to open a new PR, currently. Even this is not fully automated and requires manual review and also additions provided by SAP. E.g., only SAP is able to generate the JSON schema based on the ABAP file formats ABAP type, currently.

If we take up new object types we usually reach out to the developers responsible for this object type within SAP. Currently, we create for the most new object types draft pull requests, because we try to clarify some general/basic questions for all object types.

I am curious. ;) 
You mentioned you consider to look into DOMA.  Is there any specific reason to look into DOMA. Is there a specific use case for which you would need an ABAP file format for domains?

**Comment by larshp** [comment]
tooling, https://github.com/SAP/abap-file-formats/issues/55

**Comment by drakth** [comment]
> 

Hello Michael,

Thank you for your reply and information.

There is not specific reason for choosing domains, I found the ABAP file format repo. while researching for a way to simulate import of transport requests and somehow after lot of googling I ended up here. 
After looking for a while at the project, it peeked my interest and decided to ask. Domains seemed like a good object type to start with since I think it doesn't have much dependencies, except maybe for translations and value tables (Unless there is I'm not considering).

Again, thank you!

**Comment by schneidermic0** [comment]
I have reached out to the team responsible for DDIC domains. If you provide a PR with the ABAP type they will review your proposal and provide feedback.

I am looking forward to see your pull request. :)

Does this answer your questions?

P.S.: We cannot provide any timeline when SAP plans to provide an implementation for domains.

**Comment by drakth** [comment]
Hello,

Yes, no more questions, for now at least :)
I've created the pull request.

Thank you!

**Comment by schneidermic0** [comment]
Thank you for your pull request. :) 

Let's continue there and I think we can close this issue.
