### ISSUE TITLE
Language, exact field contents?

### ISSUE THREAD

**Issue by larshp** [SAP/abap-file-formats#34]
`masterLanguage` is part of multiple files, and it is defined as 2 characters

but what is considered correct, and what is wrong?

In SAP all user formatted languages are 2 characters upper case, but looking at something like [ISO](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes) its 2 character lower case

Suggest to make an explicit enum list of allowed values

**Comment by larshp** [comment]
still relevant, https://github.com/SAP/abap-file-formats/blob/main/file-formats/intf/examples/zif_aff_example.intf.json#L5

**Comment by larshp** [comment]
suggest following ISO standards

**Comment by larshp** [comment]
it's only possible for SAP to implement this issue, as the code for JSON generation is proprietary

**Comment by larshp** [comment]
I see this issue as an easy low hanging fruit, impacting all files in the project => ie. it should be high priority IMHO

**Comment by schneidermic0** [comment]
As mentioned above all conversions in ABAP produce 2 characters upper case (e.g. ISOLA conversion exits or transformations):
- https://help.sap.com/doc/abapdocu_cp_index_htm/CLOUD/en-US/abenst_option_format.htm?file=abenst_option_format.htm#!ABAP_ADDITION_1@1@
- https://help.sap.com/doc/abapdocu_cp_index_htm/CLOUD/en-US/abenabap_xslt_asxml_schema.htm

I think I would prefer using ISO 639-1 using small characters. 

However, I would like to check with the team how we can convert this fast in simple transformations.

**Comment by schneidermic0** [comment]
We took this topic up. Unfortunately, it turned out, that ABAP uses always upper-case language codes. 

- If we use the format option in transformations format `language` will be formatted as upper-case
see https://help.sap.com/doc/abapdocu_latest_index_htm/latest/en-US/index.htm
- Even SAP's conversion exists for language fields (like the system language) convert the language to upper case. 
see function modules CONVERSION_EXIT_ISOLA_* or CONVERT_SAP_LANG_TO_ISO_LANG

Both accept lower case iso codes as input (in our case deserialisation) but produce uppercase codes as output (in our case during serialisation).

Even if I personally would prefer small characters for language codes, I think we should stick to the representation ABAP uses in other places, too.

If no one disagrees, we should specify this in our repository documentation.

**Comment by larshp** [comment]
suggest following ISO standards

**Comment by schneidermic0** [comment]
Within the last weeks, we reiterated this topic (once more) and reached out to some more colleagues. They also suggested to use ISO-standard if the language is also used outside of ABAP systems. 

Since I mentioned some ABAP functionality to do language conversions in ABAP systems. For the conversion to ISO language codes they suggested to use class `CL_I18N_LANGUAGES`.

We planned to take this up in our current iteration (see #280)

**Comment by larshp** [comment]
class `CL_I18N_LANGUAGES` is not released, I'd expect SAP to have released stuff to convert between internal format and ISO codes

**Comment by schneidermic0** [comment]
> class CL_I18N_LANGUAGES is not released, I'd expect SAP to have released stuff to convert between internal format and ISO codes
I have sent your feedback to the colleagues responsible.

**Comment by larshp** [comment]
I've looked through https://abapedia.org/steampunk-2111-api/ but did not find anything similar

**Comment by schneidermic0** [comment]
> I've looked through https://abapedia.org/steampunk-2111-api/ but did not find anything similar

Yes, there is nothing, currently. As mentioned above I sent the feedback to my colleagues. They added it as request to their backlog.

**Comment by schneidermic0** [comment]
I think we can close this issue. If I miss anything feel free to reopen it.
