### ISSUE TITLE
abapLanguageVersion

### ISSUE THREAD

**Issue by larshp** [SAP/abap-file-formats#44]
The field `abapLanguageVersion` is really difficult

In other programming languages, the actual version of the language is rarely(?) part of the actual source code. Instead the author states the version requirements in a README (I'm thinking about Java/JavaScript/TypeScript/C++)

There is also "integrated Steampunk" which will be out sometime and do something 😄 Will a 5 year old integrated steampunk have the same languageversion as the latest cloud steampunk? I'm afraid that the list will keep increasing over time unless the purpose of the field is defined very clearly.

**Comment by esjewett** [comment]
I'd agree. I don't know of any other language that stores language version information at the file/object level. When no one does it, I start to think maybe that's because it's a bad idea. 😂 I don't see how this will play out when I am collaborating on a class with 10 other collaborators in 10 other systems. Some on Steampunk, some on 7.31, some on 7.54, some running the code and tests on Node.js using abapLint's interpreter. What `abapLanguageVersion` would this code have?

**Comment by esjewett** [comment]
@xtough Is it actually possible to identify a least-common denominator? I thought there were quite a few 7.31 language constructs that have been removed in Steampunk. I think you'd have to specify a list of supported language versions, just as JavaScript projects will specify a list of supported Node versions in their `package.json` files.

**Comment by esjewett** [comment]
Again though, I don't believe that ABAP has a concept of a least-common-denominator language version. That is to say, I think that every version has syntax that is not supported in another version.

I think the "proper" solution will be for the language version field to support multiple values to indicate that the object uses language features that are only in the intersection of the listed versions, which I doubt the ABAP runtime supports. Without that, and as currently implemented, `abapLanguageVersion` means semantically "This will run on this runtime and may or may not run on other runtimes".

**Comment by schneidermic0** [comment]
I agree, the ABAP language version does not specify which releases (like 7.02, 7.50, 7.55) are supported. I don't know any location where this can be specified in ABAP. Therefore, we cannot use it whether software will run on a specific release.

With the ABAP language version, it is "just" possible to specify which language elements and which external objects you can use in you development object. (for details refer to the [ABAP keyword documentation](https://help.sap.com/doc/abapdocu_755_index_htm/7.55/en-US/index.htm?file=abenabap_versions.htm); for other object types like data dictionary the behaviour is the same).

The ABAP language version _ABAP for Cloud Development_ is basically a subset of standard ABAP. Certain statements are not allowed any you can only use objects in your own software component or other objects which are released.

**Comment by larshp** [comment]
A: What should happen if an object is installed into a system that _does not_ support the language version specified in the file
  Example: I develop a framework in Steampunk, I'd like to reuse it on-prem

B: What should happen if an object is installed into a system that only supports a different language version than specified in the file
  Example: I develop a framework on-prem, I'd like to reuse it in Steampunk

For both examples, it would be nice if development of the framework in the other system without git diffs. From a developer perspective, its the same object, but the runtime changes. Like running a Java file on different JVMs does not cause the source Java file to change.

Depending on the scope, https://github.com/SAP/abap-file-formats/issues/86, we can consider the language version to be "transport process metadata", and specified on clone/installation locally by the developer instead of persisted in each object file.

**Comment by schneidermic0** [comment]
Maybe, let me first add some more general information about the ABAP language version to this issue:

As mentioned before the ABAP language version is a property of an object to restrict ABAP (syntax-wise and which other objects can be used/called). It can be set by the user per object in on-premise releases. To see how it is used today, you might want to refer to the following blogs:

- https://blogs.sap.com/2020/07/23/restricted-abap-and-sap-s-4hana-on-premise/
- https://blogs.sap.com/2020/06/03/restricted-abap-for-sap-cloud-platform-abap-environment/

Since it is a property that can be potentially changed by the user per object, I think we have to keep it as a property in the file formats. For me it is no data related to the deployment only, because it also specifies whether the restricted ABAP shall be used or not (for sure if it is supported in a specific release).

Let's see what this could mean to some of your questions:

> B: What should happen if an object is installed into a system that only supports a different language version than specified in the file
> Example: I develop a framework on-prem, I'd like to reuse it in Steampunk

In Steampunk, all custom code will be set to ABAP language version `cloudDevelopment` for each object. This is, how it is implemented, today. I don't expect it to be changed.


> A: What should happen if an object is installed into a system that does not support the language version specified in the file
> Example: I develop a framework in Steampunk, I'd like to reuse it on-prem

I agree we need a solution for this, because we cannot use the ABAP language version in old on-premise releases. Maybe, the following could be a solution for this: 

- If the ABAP language version existed in the on-premise system, I would keep it. This means, I can continue to develop with the same rules I have to consider in cloud development and you can keep on developing "cloud-compatible". Still, you might face issues, because in Steampunk more APIs are already released than in your actual on-premise system. This is basically the same as I would use a functionality which does not exist in the lower release.
- If the language version did not exist in the on-premise system, I would set it to `default`. You can use it there, but you might get syntax-errors if you use it again in Steampunk, because you used another API in on-premise which is not released in the cloud.

> For both examples, it would be nice if development of the framework in the other system without git diffs. From a developer perspective, its the same object, but the runtime changes. Like running a Java file on different JVMs does not cause the source Java file to change.

Yes, I can understand your use case from a developer perspective of an abapGit repository. I understand  you want to mark a whole development project (let's say a whole repository created by abapGit) with a specific ABAP Language Version. 

I am wondering whether this cannot still be added (e.g., by abapGit) so that it is possible to specify which ABAP language version shall be set during serialization of the files for a specific repository. During import/deserialization it would behave as I mentioned it in my answers to your questions A and B.

Even if this were not the simplest solution for your use case (but we have to keep other use cases in mind, too), wouldn't this cover also your use case?

**Comment by esjewett** [comment]
Would there be any downside to ABAPGit just deserializing to `default` language version everywhere, as an example?

**Comment by larshp** [comment]
I'm thinking of having abapGit serializing it to empty(not having it in the json file), always ignore what is in the system

**Comment by schneidermic0** [comment]
> Would there be any downside to ABAPGit just deserializing to `default` language version everywhere, as an example?

I see following potential disadvantage: In on-premise systems, in which ABAP language version is supported (and only there), the user might have set the ABAP language version to restrict so that the code can be used in the cloud. If abapGit would not consider this during deserialization, he might use statements or objects which are not allowed to be used in the cloud.

**Comment by larshp** [comment]
I see that as a problem to be tackled in CI. 

Example: abapGit is targeted for 702, if someone suggests a change with syntax that is not compatible with 702 it gives an error, and the change cannot be merged.

**Comment by schneidermic0** [comment]
> I see that as a problem to be tackled in CI.

OK, I see. I was just writing down my question how you would handle the local setting in the repository. ;) 
Now, I understand that you want to check the restricted ABAP statements and the released objects within the repository.

**Comment by schneidermic0** [comment]
> I'm thinking of having abapGit serializing it to empty(not having it in the json file), always ignore what is in the system

I will check with the team, whether we don't serialize `abapLanguageVersion` (in our implementation) when it is set to `standard`.

**Comment by larshp** [comment]
Assuming embedded steampunk is released to on-prem sometime, then `abapLanguageVersion = cloud` will not be enough anyhow, as allowed/released statements/objects will(?) differ between versions.

Someone developing a library in embedded steampunk version on-prem 9999, might not be compatible with embedded steampunk version 8888

**Comment by schneidermic0** [comment]
> Assuming embedded steampunk is released to on-prem sometime, then abapLanguageVersion = cloud will not be enough anyhow, as allowed/released statements/objects will(?) differ between versions.

Yes, you are right this is the same as some objects or statements do not exist in old releases. Therefore, they differ in on-premise releases.

**Comment by larshp** [comment]
If we change `abapLanguageVersion` to always be optional, then I think it will work for abapGit

**Comment by schneidermic0** [comment]
OK, I will check it with the team.

**Comment by schneidermic0** [comment]
I have talked to the team. 

Our suggestion is: `abapLanguageVersion` is optional in the file formats. We specify a default value `standard`. I.e., If `abapLanguageVersion` is not specified in the file, the version stored in a repository will be considered as  `"abapLanguageVersion": "standard"` which is the same as the default. 

During serialization, implementations can decide whether thy specify it or not.

During deserialization, ABAP systems might change the ABAP language version to the value needed in this context.

**Examples**
- The ABAP language version will be set to `cloudDevelopment` in cloud ABAP systems (aka Steampunk).
- The ABAP language version might be set to `standard` if the system does not support the specified value, yet (e.g. in a lower release)

**Comment by larshp** [comment]
👍 

not specified: its deserialization/system dependent. We should not document that it is considered as "standard", then all files where its not specified will not be cloud compatible, by "not specified is standard" definition, even though they might be

**Comment by larshp** [comment]
- [ ] Update documentation
- [ ] Adopt CHKC
- [ ] Adopt CHKO
- [ ] Adopt CHKV
- [ ] Adopt CLAS
- [ ] Adopt ENHS
- [ ] Adopt FUGR
- [ ] Adopt INTF
- [ ] Adopt NROB

**Comment by larshp** [comment]
example = https://github.com/abapGit/abapGit/issues/5921, code developed in Steampunk, importing in 740/750 systems
