### ISSUE TITLE
Compatibility: Enumeration Extensions

### ISSUE THREAD

**Issue by wurzka** [SAP/abap-file-formats#457]
Currently, we say that adding fields to an enum is a compatible change to the ABAP File Format (see [Compatible File Format Changes](https://github.com/SAP/abap-file-formats/blob/main/docs/json.md#compatible-file-format-changes)).

However, this is not correct: Systems that do not know this new value do not know how to handle it.
Extending an enum is only a compatible change if there is a default value specified for each enum which is taken when the system does not know then new field.

As consequence, all enums would have to specify a default value, no matter if required or not. (That would also give an answer to the last question of https://github.com/SAP/abap-file-formats-tools/issues/150).

The alternative is that extending enums becomes an incompatible change and leads to an increased version number.

**Comment by schneidermic0** [comment]
Thanks, @wurzka for pointing this out.

I tend to change our compatibility contract in the way that it is possible to add new enum values if there is a default value. As a consequence, if a systems  didn't support the new enumeration value (e.g., in lower releases), the file format implementations would change the value to the default value. If we want to change it this way, we need to document this behaviour as well.


@larshp Do you think this behaviour would be fine for abapGit (even if it is kind of magic)?

> The alternative is that extending enums becomes an incompatible change and leads to an increased version number.
I agree. At least, I don't see any other option if don't take up the approach mentioned above.

If we increase the format version, we might need to  introduce a compatibility handler which ensures to map the new (unknown) value to any existing value. Otherwise, we would have to stopp the import, which (I guess) won't be an option.

**Comment by larshp** [comment]
yea, its okay, we cannot cover everything in the JSON schema, if a enum value(or other value) is invalid then the development object API called should also return an error

**Comment by schneidermic0** [comment]
I am not sure, but I think if the object API raises an error, we won't be able to pull changes from the repository for this object, will we?

**Comment by larshp** [comment]
true, but then the developer must set a better value

same problem with ABAP code, only some "values" can be pulled to some systems,

```abap
CONST(sdf) = 2.
```

**Comment by schneidermic0** [comment]
Agree, with the source code. But here it is easier. You can still pull it and store the source code. It "just" will end up in a syntax error. 

For Enums this might not be possible. Let's say for value "myNewEnumValue" in the JSON wich is mapped to 'N' in the database, the system might not know this mapping. Without a mapping we cannot store it.

Therefore, the question is: If the mapping is unknown. Shall we fallback to the default value (which might lead to "syntax-errors" in the object)?

**Comment by schneidermic0** [comment]
I suggest to change our compatibility contract for enum extensions as mentioned above

> I tend to change our compatibility contract in the way that it is possible to add new enum values if there is a default value. As a consequence, if a systems didn't support the new enumeration value (e.g., in lower releases), the file format implementations would change the value to the default value. If we want to change it this way, we need to document this behaviour as well.

@wurzka Do you open a PR to update the documentation?
