### ISSUE TITLE
GH Action: JSON data validation is not working properly

### ISSUE THREAD

**Issue by albertmink** [SAP/abap-file-formats#479]
The JSON data is obviously not valid for the given JSON Schema, see 'formatVersion' that is required but not provided
https://github.com/SAP/abap-file-formats/blob/63a267d6e681ae452220c4cf7c1625ae36528ab7/file-formats/ntty/examples/z_aff_example_ntty.ntty.json#L1

**Comment by albertmink** [comment]
Object types containing other characters than [a-z] are not covered, e.g.
https://github.com/SAP/abap-file-formats/tree/main/file-formats/scp1

**Comment by albertmink** [comment]
Todo:
Algorithm might loop over JSON Schema and then pick the JSON data. As it is more likely that the JSON Schema is correct, than the JSON data. As of now, if the JSON data is corrupt, e.g. missing formatVersion, then the corresponding JSON Schema cannot be calculated. Hence, there will be no error reported.

**Comment by albertmink** [comment]
Reopened because the `todo` above.

**Comment by schneidermic0** [comment]
The check due to #480 seems to work. However, the error message is hard to understand. 

I suggest to change the error message to "JSON Example does not specify the field `formatVersion`".

Additionally, I would rename the check from "Validate JSON data" to "Validate JSON examples.

I'll create a PR
