### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by larshp** [SAP/abap-file-formats#53]
Change is constant, so over time, some fields in the JSON schemas might be moved/removed/added

Any considerations regarding versioning? eg. does a JSON file follow the old or new schema of an object

in abapGit we add https://github.com/abapGit-tests/VIEW/blob/main/src/zag_unit_testv.view.xml#L2 so that its possible for the code reading the file can make assumptions regarding the content

**Comment by larshp** [comment]
Possible Solutions:
A: version as part of serialized filename
B: version field in the JSON, and a conditional "super" schema

**Comment by larshp** [comment]
Simple conditional versioning, see https://github.com/larshp/json-versioning

![image](https://user-images.githubusercontent.com/5888506/124928473-e8c7e100-dfff-11eb-9265-6d599144e94f.png)

**Comment by larshp** [comment]
when https://github.com/SAP/abap-file-formats/issues/109 is done, we can add a small script that builds the super schema and pushes to each PR

**Comment by schneidermic0** [comment]
Just some notes related to versioning:

1. For plain text files (like `.abap` files), I think we don't need a versioning of the content, because we have just to convert the plain text
2. For structured files (like `.json` files), the file format might evolve over time and we need an indicator in which version the content was serialised/can be deserialised. We discussed following options to indicate such versions
(a) Using field `$schema` similar to the approach to specify the version in JSON schema files. This would be the URI to the schema file (e.g, `https://github.com/SAP/abap-file-formats/blob/main/file-formats/intf/intf-v1.json`
(b) Using field `$version` and indicate a version number (e.g., as simple integer).
(c) Specify the version in the file name (e.g., `if_my_interface.intf.v1.json`). 


I personally, don't prefer approach (c), because it leads to changes in the file name when the format version changes.

I am not aware of a standard way to indicate format versions in JSON files. If anybody knows a standard, please share it here. ;)

Approaches `$schema` (a) and `$version` (b) are basically similar. I am wondering why we can't use the same approach as JSON schemas. The URI could be used by tools as convenience to load the correct schema from the specified location. I see only following disadvantages compared to `$version` approach:
1. A full URI is harder to compare/analyze than a simple integer.
Maybe, we could specify that only a specific part is important to specify the schema version (e.g., only `intf-v1.json` indicates the version in the URI https://github.com/SAP/abap-file-formats/blob/main/file-formats/intf/**intf-v1.json**) to make the version identifier stable. 
2. The URI might change over time. 
We could check whether we would like to use a more stable location (e.g. storing the schemas at https://api.sap.com, https://www.schemastore.org/json/ or any other location.

**Comment by schneidermic0** [comment]
I have just seen that https://www.schemastore.org/json/ refers in some cases to schemas stored in GitHub repositories.

Example For Azure Pipelines the schema is stored at https://raw.githubusercontent.com/microsoft/azure-pipelines-vscode/v1.174.2/service-schema.json) and the schema has the `$id` `https://github.com/Microsoft/azure-pipelines-vscode/blob/main/service-schema.json`

**Comment by albertmink** [comment]
We decided to drop `$schema` from the JSON data, as suggested in #83.
At the same time we introduce a `formatVersion` field to account for versioning, see #231 and we adopt the JSON schema file name to reflect the version.

With this change, the data is independent of (possible) URI changes and the consumer has to link the data to the desired JSON schema.

**Comment by albertmink** [comment]
**Technical question**: Should the `formatVersion` rather be `const` than `enum` as by now?

Quote from JSON Schema: The `const` keyword is used to restrict a value to a single value and is new in draft07, see http://json-schema.org/understanding-json-schema/reference/generic.html#constant-values

We could simply replace the JSON schema line
https://github.com/SAP/abap-file-formats/blob/4798eb4ffece270469fde79d2410e448791b909f/file-formats/intf/intf-v1.json#L12
by
```
"const": "1"
```
Data has not to be adjusted.

**Comment by schneidermic0** [comment]
I think we can start with `const`, because one schema shall describe one version.

If we want to have a schema valid for multiple versions in the future, we could change it to enum. I would expect this as a compatible change to the schema.

**Comment by larshp** [comment]
the [deprecation keyword](http://json-schema.org/understanding-json-schema/reference/generic.html) could be used for the user to discover that there is a new version

but currently not implemented in vscode, https://github.com/microsoft/vscode-json-languageservice/issues/87
